
// this is the list of movies that should only be shown in collections and search
// never show these in suggested and other lists
hiddenMovies = [
    // Avatar
    "Avatar_1",
    "Avatar_2",
    // Shrek
    "Shrek_1",
    "Shrek_2",
    "Shrek_3",
    "Shrek_4",
    // Star Wars
    "Star_Wars_1",
    "Star_Wars_2",
    "Star_Wars_3",
    "Star_Wars_4",
    "Star_Wars_5",
    "Star_Wars_6",
    "Star_Wars_7",
    "Star_Wars_8",
    "Star_Wars_9",
    "Star_Wars_Rogue_One",
    "Star_Wars_Han_Solo_1",
    "Star_Wars_Han_Solo_1",
    // Harry Potter
    "Harry_Potter_1",
    "Harry_Potter_2",
    "Harry_Potter_3",
    "Harry_Potter_4",
    "Harry_Potter_5",
    "Harry_Potter_6",
    "Harry_Potter_7",
    "Harry_Potter_8",
    // Marvel
    "Spiderman_Toby_1",
    "Spiderman_Toby_2",
    "Spiderman_Toby_3",
    "Spiderman_Andrew_1",
    "Spiderman_Andrew_2",
    "Captain_America_1",
    "Captain_Marvel_1",
    "Iron_Man_1",
    "Iron_Man_2",
    "The_Hulk_1",
    "Thor_1",
    "Avengers_1",
    "Thor_2",
    "Iron_Man_3",
    "Captain_America_2",
    "Guardians_Of_The_Galaxy_1",
    "Guardians_Of_The_Galaxy_2",
    "Avengers_2",
    "Ant_Man_1",
    "Captain_America_3",
    "Black_Widow_1",
    "Spiderman_Tom_1",
    "Black_Panther_1",
    "Doctor_Strange_1",
    "Thor_3",
    "Ant_Man_2",
    "Avengers_3",
    "Avengers_4",
    "Loki",
    "Spiderman_Tom_2",
    "Shang_Chi_1",
    "Eternals_1",
    "Spiderman_Tom_3",
    "Doctor_Strange_2",
    "Thor_4",
    "Black_Panther_2",
    "Ant_Man_3",
    "Guardians_Of_The_Galaxy_3",
    // Rocky Balboa
    "Rocky_1",
    "Rocky_2",
    "Rocky_3",
    "Rocky_4",
    "Rocky_5",
    "Rocky_6",
    "Creed_1",
    "Creed_2",
    "Creed_3",
]
